swagger: '2.0'
info:
  description: >-
    Extract knowledge and find offers from the given sentence
  version: 1.0.0
  title: Smart-Resource-and-Service-Discovery-application 
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: almpertoerspamer@intracom-telecom.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 127.0.0.1
basePath: /
tags:
  - name: discoveroffer
    externalDocs:
      description: Find out more
      url: 'https://github.com/5GZORRO/Smart-Resource-and-Service-Discovery-application'
schemes:
  - https
  - http
paths:
  /discoveroffer:
    get:
      tags:
        - dicoveroffer
      summary: Extract knowledge and find offers from the given sentence
      description: ''
      operationId: discoveroffer
      consumes:
        - application/string
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: sentence
          description: Sentence to extract knowledge from
          required: true
      responses:
        '200':
          description: "successful operation"
          schema:
            $ref: "#/definitions/dicoveroffer"          
        "500":
          description: "Internal Server Error"
        "404":
          description: "The requested URL was not found"
          
definitions:
  dicoveroffer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int"
      type:
        type: "string"
      format:
        type: "string"
      slice_segment:
        type: "string"
      latitude:
        type: "number"
        format: "float"
      longitude:
        type: "number"
        format: "float"
      offered_price:
        type: "number"
        format: "float"        
      VSB:
        type: "string"
      total_score:
        type: "string"
    xml:
      name: "User"
